// Exports the canonical learning content (server/content) into a PHP file the
// PHP backend reads at runtime: php/api/content.full.php.
//
// The output contains the FULL content — including quiz answers and mission
// rubric keywords — so it must never be web-served directly. It is written as a
// .php file that `return`s the data; a direct browser hit executes PHP and emits
// nothing, so the answers can't leak (unlike a plain .json file).
//
// Run after editing any server/content/*.js:  node scripts/export-content.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import {
  modules,
  XP,
  ranks,
  stages,
  badgeCatalog,
  stageBadgeMap,
} from '../server/content/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(__dirname, '..', 'php', 'api', 'content.full.php');

// Everything the PHP layer needs. PHP derives the public (answer-stripped)
// projection, prompt/mission indexes and totals from this at runtime.
const payload = { modules, XP, ranks, stages, badges: badgeCatalog, stageBadgeMap };

const json = JSON.stringify(payload, null, 2);

// Nowdoc (single-quoted heredoc) — no PHP interpolation, and JSON never contains
// the closing marker on its own line, so this is safe without escaping.
const php = `<?php
// AUTO-GENERATED by scripts/export-content.mjs — do not edit by hand for the app
// (the admin panel may rewrite this file when content is edited in production).
// Canonical source: server/content/*.js
return json_decode(<<<'ARENA_CONTENT_JSON'
${json}
ARENA_CONTENT_JSON, true);
`;

writeFileSync(outFile, php);
const counts = {
  modules: modules.length,
  lessons: modules.reduce((n, m) => n + m.lessons.length, 0),
  prompts: modules.reduce((n, m) => n + m.prompts.length, 0),
  missions: modules.reduce((n, m) => n + m.missions.length, 0),
  badges: badgeCatalog.length,
};
console.log('Wrote', path.relative(process.cwd(), outFile));
console.log(counts);
